name: ColoredChat
version: '${project.version}'
main: com.greenjon902.coloredchat.ColoredChat
api-version: 1.18
authors: [ GreenJon902 ]
description: Get colorful text in chat
website: https://github.com/GreenJon902
